function [fitresult, gof] = createFit(X, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 4' fit:
%      X Input: X
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Jan-2025 13:34:39


%% Fit: 'untitled fit 4'.
[xData, yData] = prepareCurveData( X, y );

% Set up fittype and options.
ft = fittype( 'rat12' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.107769015243743 0.906308150649733 0.879653724481905 0.817760559370642];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% fig=figure(99);
% clf(fig);
% h = plot( fitresult, xData, yData );
% legend( h, 'y vs. X', 'untitled fit 4', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'X', 'Interpreter', 'none' );
% ylabel( 'y', 'Interpreter', 'none' );
% grid on


