function [fitresult, gof] = createFit(T, lambda)
%CREATEFIT1(T,LAMBDA)
%  Create a fit.
%
%  Data for 'lambda' fit:
%      X Input: T from tab
%      Y Output: lambda from tab
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Jan-2025 15:37:03


%% Fit: 'lambda'.
[xData, yData] = prepareCurveData( T, lambda );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'lambda' );
h = plot( fitresult, xData, yData );
legend( h, 'lambda vs. T', 'lambda', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T', 'Interpreter', 'none' );
ylabel( 'lambda', 'Interpreter', 'none' );
grid on


