%% Property functions of DC04 steel (1.0337)
% GNU General Public License v3.0
% By Stefan Thanheiser: https://orcid.org/0000-0003-2765-1156
%
% Part of the paper:
%
% Thanheiser, S.
% Molerus and Wirth's Heat Transfer Model for Bubbling Fluidized Beds: 
% Proposal for an Extended Model Including Immersed Tube Banks and Particle 
% Cross-Flow
%
% All required files for this class can be found in the software
% repository: 
% https://doi.org/10.5281/zenodo.15576950
%
%
%
% This class describes the thermo-physical properties of DC04 steel 
% (1.0337) according to:
%
% Florian Sunderbrink, Rosink
%
%
%Requires all files packaged in the class folder and on the MATLAB path
%
%Required products, version 24.1:
%   - MATLAB
%   - Curve Fitting Toolbox
%Data files:
%   - prop.xls
%   - fits.mat --> can be created with the createConstants function


classdef DC04
    %All parameters and results in SI base units


    %% Property functions
    methods(Static)
        function lambda=lambda(T)
            %Thermal conductivity
            load(['@DC04',filesep,'fits.mat'],'T_lambda');

            valid=200<=T & T<=600;    %Estimated range of validity

            lambda=NaN(size(T));
            lambda(valid)=T_lambda(T(valid));
        end


        function createConstants()
            %Creates the constants from the Excel file
            tab=readtable(['@DC04',filesep,'prop.xls']);
            tab.T=tab.T+273.15;

            T_lambda=DC04.createFit(tab.T,tab.lambda);

            save(['@DC04',filesep,'fits.mat'],'T_lambda');
        end
    end


    %% Auxilliary Functions
    methods(Static, Access=private)
        function [fitresult,gof] = createFit(T,lambda)
        % Fit of lambda vs. temperature
        % Auto-generated by MATLAB using the curve fitter
        
        [xData, yData] = prepareCurveData( T, lambda );
        
        % Set up fittype and options.
        ft = fittype( 'poly3' );
        
        % Fit model to data.
        [fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );
        
        % Plot fit with data.
        figure( 'Name', 'lambda' );
        h = plot( fitresult, xData, yData );
        legend( h, 'lambda vs. T', 'lambda', 'Location', 'NorthEast', 'Interpreter', 'none' );
        % Label axes
        xlabel( 'T', 'Interpreter', 'none' );
        ylabel( 'lambda', 'Interpreter', 'none' );
        grid on
        end
    end
end